### PR TITLE
Add Python 3.11 to setup.cfg classifiers list

### PR DESCRIPTION
**Pull request by xrisk**
I have verified that tests are passing.

### CODE REVIEW

**Comment by xrisk** [comment]
Oh, I realize this will probably need updates to GH actions.

**Comment by eggplants** [comment]
> Oh, I realize this will probably need updates to GH actions.

**Comment by eggplants** [comment]
@akamhy This might be helpful to keep actions fresh.

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions

**Comment by akamhy** [comment]
@xrisk, I will create new release by next Sunday. Thanks.

**Pull request merged**
