### PR TITLE
Fix Pylint errors were pointed out by codacy

### PR DESCRIPTION
**Pull request by eggplants**
- use `None` instead of `[]` as default param
  - ref: https://stackoverflow.com/a/26320938
- stop overwriting built-in functions
- avoid `no-value-for-parameter`
- decrease complexity

### CODE REVIEW

**Comment by akamhy** [comment]
I am resolving the conflict. Your names are better than mine and are also typed.

**Comment by eggplants** [comment]
Oops, overlooked #132. Sorry!

**Comment by eggplants** [comment]
Does pep8speaks ignore flake8 configuration in setup.cfg?

**Comment by akamhy** [comment]
> Does pep8speaks ignore flake8 configuration in setup.cfg? `max-line-length = 88` in setup.cfg, but `77` in pep8speaks.

It is not supposed to ignore it as per the 2nd last point in <https://github.com/OrkoHunter/pep8speaks#configuration>.  Let me push a `.pep8speaks.yml` into the master with `flask8` in `scanner.linter`.

**Comment by eggplants** [comment]
OK, Please try it.

**Comment by akamhy** [comment]
> OK, Please try it.

Should be fixed in https://github.com/akamhy/waybackpy/commit/9d9cc3328b6c43b3915017434c48470134a98bad and it should now respect the setting in setup.cfg

**Review by akamhy — APPROVED** [review]
LGTM

**Comment by eggplants** [comment]
I refactored codes to decrease complexity. 4df8364a1a69e1c920bc77260098be09a87ddcdb

**Review by akamhy — APPROVED** [review]
I can not find any obvious issues. Merge if you want to.

**Pull request merged**
