### PR TITLE
Typing

### PR DESCRIPTION
**Pull request by eggplants**
Closes: #127 

mypy configuraion:

https://github.com/eggplants/waybackpy/blob/639159e304f4aa31f7d0af609e1253b5b5d2be3e/setup.cfg#L70-L74

```ini
[mypy]
python_version = 3.9
show_error_codes = True
pretty = True
strict = True
```

---

```shellsession
$ mypy -p waybackpy -p tests
Success: no issues found in 17 source files
```

### CODE REVIEW

**Comment by eggplants** [comment]
Does pep8speaks ignore flake8 configuration in setup.cfg?

**Comment by eggplants** [comment]
https://app.codacy.com/gh/akamhy/waybackpy/pullRequest?prid=8826635

`license` and `filter` are same names as built-in functions. Could I rename them?

**Comment by akamhy** [comment]
> https://app.codacy.com/gh/akamhy/waybackpy/pullRequest?prid=8826635
> 
> `license` and `filter` are same names as built-in functions. Could I rename them?

Yes but actually No, what I meant is to let the name stay the same for command-line usage but change them in the main function by leveraging the order specified at <https://click.palletsprojects.com/en/8.0.x/options/#name-your-options>.

How about adding `--showlicense` and `--cdxfilter` respectively to the [option()](https://click.palletsprojects.com/en/8.0.x/api/#click.option) decorator of `license` and `filter`  and using them in the main function?

If you agree then please go ahead and make the required changes or suggest what you think would be better.

**Review by akamhy — APPROVED** [review]
LGTM

**Pull request merged**
